version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: raj123
      POSTGRES_USER: raj
      POSTGRES_DB: demo
  app:
    image: my-node-app
    ports:
      - 13000:3000
